---
title: "Gráficos con R"
format: live-html
webr:
  packages:
  - ggplot2
  - gapminder
  - dplyr
engine: knitr
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

<script>
function showSection(sectionId) {
  const sections = document.querySelectorAll('.section');
  sections.forEach(section => section.style.display = 'none');
  document.getElementById(sectionId).style.display = 'block';
}
</script>

<div id="section1" class="section">
  ## Introducción
  Vamos a utilizar el paquete `ggplot2` que implementa la _gramática de los gráficos_ desarrollada por Leland Wilkinson...
  <button onclick="showSection('section2')">Next</button>
</div>

<div id="section2" class="section" style="display:none;">
  ## Ejemplo de la gramática en un gráfico
  Vamos a ver un ejemplo de estos componentes en un gráfico...
  <button onclick="showSection('section3')">Next</button>
</div>

<div id="section3" class="section" style="display:none;">
  ## Cambiemos algunas propiedades
  Supongamos que queremos cambiar los ejes del gráfico...
  <button onclick="showSection('section4')">Next</button>
</div>

<div id="section4" class="section" style="display:none;">
  ## Hagamos un gráfico de lineas
  Vamos a realizar otros gráficos utilizando los datos en `gapminder`...
  <button onclick="showSection('section5')">Next</button>
</div>

<div id="section5" class="section" style="display:none;">
  ## Hagamos un gráfico de barras
  Hay dos formas de hacer un gráfico de barras en `ggplot2`...
  <button onclick="showSection('section6')">Next</button>
</div>

<div id="section6" class="section" style="display:none;">
  ## Hagamos un gráfico de área
  Vamos a transformar el gráfico anterior a áreas...
</div>